### ISSUE TITLE
WARNING: MALWARE

### ISSUE THREAD

**Issue by Dragon-Batch** [1valdis/bass-booster#2]
this is malware inside the .js there is a exe file that is encoded in base64 and it gets executed once the js file is ran

**Comment by 1valdis** [comment]
That's a bold statement. Care to elaborate?

You're probably talking about the ffmpeg-worker-mp4.js . It is taken from the package https://github.com/Kagami/ffmpeg.js and wasn't modified. If you suggest there are issues with that, please open an issue there. Also, since it's only needed for conversion to mp3, it's not even downloaded, let alone executed, until the user presses save as mp3 button.

**Comment by 1valdis** [comment]
No reply, closing.
